### ISSUE TITLE
Uploading to the GROUP wrong filename

### ISSUE THREAD

**Issue by matijagrcic** [PerfectoMobileSA/fastlane-plugin-perfecto#2]
Hi,

When uploading to the group the filename in the UI doesn't show only the IPA name but everything that is specified under the `perfecto_media_location`.

For example I'm using `GROUP:My QA Group/some-app.ipa`

When using `PRIVATE:some-app.ipa` then the filename is correct.

I'm referring to the naming convention from the [help](https://developers.perfectomobile.com/display/PD/Legacy+%7C+Upload+Item+to+Repository)

```
artifactLocator: Unique artifact identifier.

Format:
{folderType}:{artifactKey}

where:
folderType: Defines privileges of accessibility. 

Possible values:

> PRIVATE: Only the owner has access to the artifact.
> GROUP: Only users related to the owner’s group will have access to the artifact.
> PUBLIC: All users have access to the artifact.

artifactKey: Unique identifier of the artifact
```
[Ref](https://help.perfecto.io/perfecto-help/content/perfecto/automation-testing/upload_item_to_repository.htm)

Is there a scheme when uploading so that only a specific group can see the artifacts? 
Setting `perfecto_media_location`  to `GROUP:some-app.ipa` is ok in the UI but doesn't that mean all users can see the artifact?

**Comment by genesisthomas** [comment]
Dear @matijagrcic, Thanks for raising an issue. Please note that this tool uses this [latest upload api](https://help.perfecto.io/perfecto-help/content/perfecto/automation-testing/upload_item_to_repository.htm) under the hood. [Interesting content: GROUP: Only users related to the owner’s group will have access to the artifact.]

Regarding your question: Please refer here for [Repository documentation](https://help.perfecto.io/perfecto-help/content/perfecto/assets-and-setup/manage_the_repository.htm?Highlight=group%20repository).
In short, any files present in GROUP: will be visible only to users with group access, be it GROUP:some-app.ipa or GROUP:My QA Group/some-app.ipa.

E.g. "My QA Group" is an imaginary folder/locator also seen in UI which was created just so that we can group similar files in a folder structure. [Interesting content: The locator: This is the virtual path that you will use in your automation code. By default, it consists of the virtual folder name and the file name (for example: My group: sample-app.apk), but you can insert additional levels between the virtual folder and the file name.] 

Kindly raise a Perfecto support case for faster response. I will close this issue for now unless you want to know more. :)

**Comment by matijagrcic** [comment]
Thanks for getting back @genesisthomas. I've figured out the locator is just an imaginary folder and doesn't mean anything in the new UI as long as GROUP is provided all members will see it. Would be nice if the filtering can be done in future.

**Comment by genesisthomas** [comment]
My pleasure. Kindly raise a support case from [here](https://support.perfecto.io) with your nice feature requirement for the new API
